### PR TITLE
Json parsing error on Windows machine

### LINKED ISSUE #1: Json parsing error on Windows machine
I am trying to integrate this into our Visual Studio Team Services CI environment, but it's throwing a SyntaxError when trying to parse the git log message because the JSON doesn't return with the values enclosed in quotes on Windows machines. 

Here is the command causing the issue in **commit-info.js**: 
`let command = 'git log -1 --no-color --decorate=short --pretty=format:'${newFormat}' HEAD';`

The error is then thrown on this line when trying to parse the result of that command:
`let commitInfo = JSON.parse(stdout);`

This error is thrown because the JSON is formatted like this on Windows machines:
`{shortRevision:1e2d8ab,revision:1e2d8ab86d94be5e6492c44cec2ee57f1de1ec49,date:2 weeks ago,...}`

Instead of like this on Linux machines:
`{"shortRevision":"1e2d8ab","revision":"1e2d8ab86d94be5e6492c44cec2ee57f1de1ec49","date":"2 weeks ago",...}`

### PR DESCRIPTION
**Pull request by kwyss88**
Resolves #1

### CODE REVIEW

**Comment by kwyss88** [comment]
@mattyboy The changes I made don't seem to have any effect on the test that's failing. Can you take a look and see if that's possibly a false positive?

**Comment by mattyboy** [comment]
Keith I'm trying to find a solution that would allow for 100% code coverage and not introduce an OS switch. The best approach I can find for that is to change the format to something that works across platforms, then process that into JSON afterwards. 

There is a [branch](/mattyboy/istanbul-slack-notify/tree/BUG-001-kwyss88) open with this approach in mind, are you able to confirm the the new git command would work? Or identify a more suitable command
`git log -1 --no-color --decorate=short --pretty=format:'%h$$$%H$$$%cr$$$%f$$$%an$$$%ae$$$%d' HEAD`

**Comment by kwyss88** [comment]
Yep, I tested that branch in my environment and it works. Great solution to the test coverage problem. Thanks for your help on this!

**Comment by mattyboy** [comment]
Closing pull request in favour for other fix.

**Pull request closed without merging**
